version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: steelmaster-n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=${DB_HOST}
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=${DB_NAME}
      - DB_POSTGRESDB_USER=${DB_USER}
      - DB_POSTGRESDB_PASSWORD=${DB_PASS}
      - WEBHOOK_URL=http://n8n.steelmaster.atlasbot.tech
    ports:
      - "8585:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
