version: '3.8'

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    restart: always
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=aws-0-sa-east-1.pooler.supabase.com
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=postgres
      - DB_POSTGRESDB_USER=postgres.lgptxdzythxkoucafwjs
      - DB_POSTGRESDB_PASSWORD=SteelMaster2026@Atlas
      - DB_POSTGRESDB_SSL_REJECT_UNAUTHORIZED=false
      - WEBHOOK_URL=http://n8n.steelmaster.atlasbot.tech
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
